### ISSUE TITLE
org.rosuda.REngine.Rserve.RserveException: assign failed

### ISSUE THREAD

**Issue by ifo1999** [s-u/Rserve#146]
Hello. I have to tell you in advance that I appreciate for providing the library.

I have an error like below sometimes.

I can not reproduce this situation because When I test with the same input data but it works well

Last line is the location where error occurs

Could you help me?
 

org.rosuda.REngine.Rserve.RserveException: assign failed
	at org.rosuda.REngine.Rserve.RConnection.assign(RConnection.java:312)
	at com.ssfashion.bigdata.qm.vo.QMDao.setRInputList(QMDao.java:414)

		REXP reqMst = REXP
				.createDataFrame(new RList(
						new REXP[] {
								new REXPString(prod_no                           ),
								new REXPString(gubun                             ),
								new REXPString(mixrt                             ),
								new REXPString(dsgn_cd                           ),
								new REXPString(physico_excm_chem4                ),
								new REXPString(physico_excm_chem1                ),
								new REXPString(physico_excm_chem2                ),
								new REXPString(kc_excm4                          ),
								new REXPString(kc_excm2                          ),
								new REXPString(gb_excm4                          ),
								new REXPString(original_kor_yn                   ),
								new REXPString(original_eng_yn                   ),
								new REXPString(original_cha_yn                   ),
								new REXPString(copy_kor                          ),
								new REXPString(copy_kor_yn                       ),
								new REXPString(copy_eng                          ),
								new REXPString(copy_eng_yn                       ),
								new REXPString(copy_cha                          ),
								new REXPString(copy_cha_yn                       ),
								new REXPString(coating_yes_yn                    ),
								new REXPString(coating_no_yn                     ),
								new REXPString(specimen_cnt                      ),
								new REXPString(safety_kc_fiber1_yn               ),
								new REXPString(safety_kc_fiber2_yn               ),
								new REXPString(safety_kc_fiber3_yn               ),
								new REXPString(mandatory_test_yn                 ),
								new REXPString(addition_allergy_yn               ),
								new REXPString(chun_cowskin                      ),
								new REXPString(injo_cowskin                      ),
								new REXPString(chun_pelt                         ),
								new REXPString(gb_mixed_rate                     ),
								new REXPString(gb_18401                          ),
								new REXPString(retest3                           ),
								new REXPString(test_eval                         ),
								new REXPString(test_frefro                       ),
								new REXPString(test_prod                         ),
								new REXPString(mat_outshell                      ),
								new REXPString(mat_lining                        ),
								new REXPString(mat_color                         ),
								new REXPString(gb_excm2                          ),
								new REXPString(physico_excm_machine              ),
								new REXPString(physico_excm_hand                 ),
								new REXPString(physico_excm_dry                  ),
								new REXPString(physico_excm_suit                 ),
								new REXPString(physico_excm_ladies               ),
								new REXPString(physico_excm_coat                 ),
								new REXPString(physico_excm_casual_outdoor       ),
								new REXPString(phy_knit_sweater                  ),
								new REXPString(physico_excm_down                 ),
								new REXPString(physico_excm_other                ),
								new REXPString(gb_other                          ),
								new REXPString(mat_cls_cd                        ),
								new REXPString(wear_kind                         ),
								new REXPString(wash_kind                         ),
								new REXPString(prod_excm5                        ),
								new REXPString(prod_excm3                        ),
								new REXPString(prod_excm2                        ),
								new REXPString(kc_safety_yn                      ),
								new REXPString(compliance_yn                     ),
								new REXPString(adult_yn                          ),
								new REXPString(print_yn                          ),
								new REXPString(simple_y                          ),
								new REXPString(wr_y                              ),
								new REXPString(ph_garment_y                      ),
								new REXPString(kc_garment_y                      ),
								new REXPString(pay_ph_inspect_fee_yn             ),
								new REXPString(pay_gb_inspect_fee_yn             ),
								new REXPString(pay_kc_inspect_fee_yn             ),
								new REXPString(pay_prod_inspect_fee_yn           ),
								new REXPString(specimen_etc                      ),
								new REXPString(prod_excm_wash                    ),
								new REXPString(mat_rate_cd                       ),

						},
						reqMstColNm));

		rcon.assign("reqMst", reqMst);

**Comment by ifo1999** [comment]
Rconnection object was shared at the same time.(It was created by autowired) that caused this problem.
I changed the declaretion from class to method. It was solved
