### ISSUE TITLE
RTalk.request(int cmd, String par) and other commands don't support large packets

### ISSUE THREAD

**Issue by cannshui** [s-u/Rserve#67]
I have a big script whose length is 24.2 MB(2147483647 bytes). While execute it by `RConnection.eval()`, I get a `java.lang.ArrayIndexOutOfBoundsException` exception. After I go inside the exception stack, I check out there is a problem here  `if ((sl&3)>0) sl=(sl&0xfffffc)+4`. 

Paste the full method here for easy reading:

```
public class RTalk {

  ...

 /** sends a request with one string parameter attached
@param cmd command
@param par parameter - length and DT_STRING will be prepended
@return returned packet or <code>null</code> if something went wrong */
public RPacket request(int cmd, String par) {
try {
        byte[] b=par.getBytes(RConnection.transferCharset);
        int sl=b.length+1;

        /* Is 0xfffffc a little smaller? */
        if ((sl&3)>0) sl=(sl&0xfffffc)+4; // make sure the length is divisible by 4
    byte[] rq=new byte[sl+5];
        int i;
    for(i=0;i<b.length;i++)
            rq[i+4]=b[i];
        while (i<sl) { // pad with 0
            rq[i+4]=0; i++;
        };
    setHdr(DT_STRING,sl,rq,0);
    return request(cmd,rq);
} catch (Exception e) {
    e.printStackTrace();
}
return null;
}

...

}
```

To sum up, if `par`'s length `sl` isn't divisible by 4 and bigger than `0xffffff`, there would be a issue.

**Does it ?**

Exception stack :

```
java.lang.ArrayIndexOutOfBoundsException: 8643397
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:245)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:258)
    at com.cas.pas.R.impl.RInvokerServiceImpl.invokeRScript(RInvokerServiceImpl.java:106)
    at com.cas.pas.data.MockTest.invokeAnyRScriptTest(MockTest.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
org.rosuda.REngine.Rserve.RserveException: eval failed
```

**Comment by s-u** [comment]
Yes, the current `request(int, String)` implementation doesn't support large packets. It was never expected that one would call it with a string anywhere close to that limit (24-bit). Note that it is not the only place, only `eval(REXP, REXP, boolean)` and `assign(String, REXP)` support large packets, other functions don't. So a work-around may be to use something like

```r
e.assign(".script", new REXPString(script));
REXP x = e.eval("eval(parse(text=.script))");
```

**Comment by cannshui** [comment]
Thanks for your great reply.

I'm going to describe it in a more detail way.

My R serve env:

 - OS: Ubuntu 15.10 b4-bit
 - R: version 3.2.2 (2015-08-14) -- "Fire Safety"
 - Rserve package: 1.7-3

My Java Client env:

 - OS: win7 64-bit
 - JDK: 1.7
 - REngine jars: org.rosuda.REngine:REngine:2.1.0, org.rosuda.REngine:Rserve:1.8.1

I have two large scripts, one 15.1 M (15,886,405 bytes, **smaller than 16 M**), another 24.2 M (25,420,762 bytes). They are all actual scripts generated by production Java Code that both have a great amount of data.

Follows are tries to execute them in three ways.

##### 1. Avoid running into `if ((sl&3)>0) sl=(sl&0xfffffc)+4`.

I do a trick by removing some blanks so to make `sl & 3 == 0` and avoid running `sl=(sl&0xfffffc)+4`, maybe generate a `RPacket` properly(?).

I still use `RConnection.eval()` to execute them. The 15.1 M script is executed successfully. While the 24.2 M one, I get a Java Exception `org.rosuda.REngine.Rserve.RserveException: eval failed, request status: error code: 127`, and **Error: could not find function "ary"** in my ubuntu opened terminal.

Does it because the generated packet exceeds 16 M?

##### 2. Using your advice.

I fix my code as follow with your advice:

	...stuff code before
	rconn.assign(".script", new REXPString(script));
	REXP x = rconn.eval("eval(parse(text=.script))");
	//rconn.eval(script);
	...stuff code after

This time after execution. The 15.1 M script causes a Java Excetion `org.rosuda.REngine.Rserve.RserveException: eval failed, request status: error code: 127`, and **Error: C stack usage   32593648 is too close to the limit** in ubuntu terminal. The 24.2 M one causes the same Java Excetion, but the error message in ubuntu terminal becomes **Error: C stack usage  52139416 is too close to the limit**.

So, it seems this solving is failed?

##### 3. Another trick way, `eval` the large script line by line.

I tried something like this:

	class RConnectionWrapper extends RConnection {

		...

		/* rewrite eval method hope doing some help */
		@Override
		public REXP eval(String cmd) throws RserveException {
			int len = cmd.length();
			if (len < 0xffffff) {
				return super.eval(cmd);
			}
			// large script, eval line by line, and each line is smaller than 0xffffff
			String[] lines = cmd.split("\n");
			for (String line: lines) {
				super.eval(line);
			}
			// the eval result is lost
			return null;
		}

		...

	}

It seems the large script is executed successfully. But I don't know if there may be something wrong going inside. 

Sorry to say, I'm quite new to R language. And, my job is just to execute kinds of scripts to output images. Does any more advice for my situation?

Thanks.
